#!/usr/bin/env python3
"""audit_against_ssots.py — send ONE artifact plus the SSOTs it was generated from to a DIFFERENT
LLM, and ask that LLM to audit the artifact against those SSOTs. Standard library only.

  python3 tools/audit_against_ssots.py \
      --artifact  path/to/ARTIFACT.md \
      --ssot      path/to/source1.md  --ssot path/to/photo.jpg  [--ssot ...] \
      --generator "Claude Fable 5.1" \
      [--model gemini-3.7-flash] [--key-var GEMINI_API_KEY] [--out runs/]

An LLM API call has FIVE parts. The functions below are named after them so the file reads top to
bottom in the same order the call happens. This is the lesson's vocabulary:

  1. WHERE  — the URL: which host, which model, which method.                      (part_1_where)
  2. WHO    — the header that proves who is asking: the key, read from the          (part_2_who)
              environment, never typed into a file, never printed.
  3. WHAT   — the body: the message parts. A "file bundle" is nothing more than      (part_3_what)
              one part per file, in order, each labelled, images as base64.
  4. HOW    — generationConfig: temperature, output format, output cap.             (part_4_how)
  5. THEN   — the response: find the text, parse it, save the raw bytes AND a        (part_5_then)
              human-readable report, with a manifest of exactly what was sent.

Nothing here is specific to auditing except the prompt. Swap the prompt and the same five parts
extract a census, grade an exit ticket, or summarise a paper.

Written for Krystal Martinez's Python for Poets (and Model Evaluators) lesson L01, 2026-09-19, by
Flaudechamba A.-L. Formative Horizon v01 (Claude Fable 5.1). Grounded in the working census harness
`census_gemini_2026-09-19_v04_I.py` in the REME workbench, which made ~500 successful calls with the
same WHERE / WHO / HOW shape on the same day.
"""
from __future__ import annotations

import argparse
import base64
import datetime as dt
import hashlib
import json
import mimetypes
import os
import re
import sys
import time
from pathlib import Path
from urllib import error, request

API = "https://generativelanguage.googleapis.com/v1beta"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic"}


# ─────────────────────────────────────────────────────────────────────────────────────────────
# 1. WHERE — the URL
# ─────────────────────────────────────────────────────────────────────────────────────────────
def part_1_where(model: str) -> str:
    """Host + version + model + method. The method name (generateContent) is the verb."""
    return f"{API}/models/{model}:generateContent"


# ─────────────────────────────────────────────────────────────────────────────────────────────
# 2. WHO — the header
# ─────────────────────────────────────────────────────────────────────────────────────────────
def part_2_who(key_var: str) -> dict:
    """The key comes from the ENVIRONMENT, put there by `set -a; . <path>; set +a` in the shell.
    The program never sees a file of secrets and never prints the value."""
    key = os.environ.get(key_var)
    if not key:
        sys.exit(f"FATAL: {key_var} is not in the environment. In the shell first: set -a; . <secrets path>; set +a")
    return {"x-goog-api-key": key, "Content-Type": "application/json"}


# ─────────────────────────────────────────────────────────────────────────────────────────────
# 3. WHAT — the body (the file bundle + the prompt)
# ─────────────────────────────────────────────────────────────────────────────────────────────
def file_part(label: str, p: Path) -> list[dict]:
    """One file → one or two parts. Text files ride as text under a header line; images ride as
    base64 with a MIME type, preceded by a text label so the model knows which file it is looking at."""
    if p.suffix.lower() in IMAGE_SUFFIXES:
        mime = mimetypes.guess_type(p.name)[0] or "image/jpeg"
        data = base64.b64encode(p.read_bytes()).decode("ascii")
        return [{"text": f"=== {label}: {p.name} (image) ==="},
                {"inlineData": {"mimeType": mime, "data": data}}]
    return [{"text": f"=== {label}: {p.name} ===\n{p.read_text(encoding='utf-8', errors='replace')}"}]


AUDITOR_ROLE = """You are an independent auditor. The ARTIFACT below was generated by a different model
({generator}). You are not that model; do not defer to it and do not repair it. Your only job is to
compare every checkable claim in the ARTIFACT against the SSOTs (single sources of truth) it was
generated from, and report what you find. Quote both sides verbatim. Where an SSOT is an image,
describe the exact region you read (page, line, colour, position). If you cannot verify a claim
from the SSOTs provided, say NOT_IN_SSOT — never fill a gap from your own knowledge.

Return ONLY JSON with this shape:
{{
  "artifact": "<file name>",
  "ssots_consulted": ["<file name>", ...],
  "findings": [
    {{"id": "F1",
      "claim_in_artifact": "<verbatim quote>",
      "location_in_artifact": "<heading / bullet / line>",
      "ssot": "<file name>",
      "evidence_in_ssot": "<verbatim quote, or image region description>",
      "verdict": "SUPPORTED | CONTRADICTED | NOT_IN_SSOT | UNCERTAIN",
      "note": "<one sentence, only if the verdict needs it>"}}
  ],
  "omissions": [
    {{"in_ssot": "<file name>", "evidence": "<what the SSOT contains that the artifact left out>", "note": ""}}
  ],
  "overall": {{"supported": 0, "contradicted": 0, "not_in_ssot": 0, "uncertain": 0,
               "summary": "<two sentences, findings only, no praise>"}}
}}
Audit every highlighted span, every transcribed marginal note, every colour assignment and every count
in the ARTIFACT. Prefer more findings over fewer. Numbers in "overall" must equal the counts in "findings"."""


def part_3_what(artifact: Path, ssots: list[Path], generator: str, task: str) -> tuple[dict, list[dict]]:
    """Assemble the bundle in a fixed order: task → each SSOT → the artifact last, so the model reads
    the ground truth before the thing being judged. Returns (systemInstruction, contents)."""
    parts: list[dict] = [{"text": task}]
    for i, s in enumerate(ssots, 1):
        parts += file_part(f"SSOT {i} of {len(ssots)}", s)
    parts += file_part("ARTIFACT UNDER AUDIT", artifact)
    system = {"parts": [{"text": AUDITOR_ROLE.format(generator=generator)}]}
    contents = [{"role": "user", "parts": parts}]
    return system, contents


# ─────────────────────────────────────────────────────────────────────────────────────────────
# 4. HOW — generation settings
# ─────────────────────────────────────────────────────────────────────────────────────────────
def part_4_how(max_output_tokens: int = 8192) -> dict:
    """Temperature 0 so a re-run is as repeatable as the API allows; JSON out so THEN can parse it;
    an output cap so a runaway answer cannot cost more than intended."""
    return {"temperature": 0, "responseMimeType": "application/json", "maxOutputTokens": max_output_tokens}


# ─────────────────────────────────────────────────────────────────────────────────────────────
# The call itself — WHERE + WHO + WHAT + HOW go out; the raw response comes back
# ─────────────────────────────────────────────────────────────────────────────────────────────
class Quota(Exception):
    """HTTP 429 with a quota message: this model is spent for now. Try the next rung."""


def send(url: str, headers: dict, body: dict, tries: int = 3, timeout: int = 300) -> dict:
    data = json.dumps(body).encode()
    for i in range(tries):
        try:
            req = request.Request(url, data=data, headers=headers, method="POST")
            with request.urlopen(req, timeout=timeout) as r:
                return json.loads(r.read().decode())
        except error.HTTPError as e:
            msg = " ".join(e.read().decode(errors="replace").split())
            if e.code == 429 and re.search(r"quota|RESOURCE_EXHAUSTED", msg, re.I):
                raise Quota(msg[:400])
            if e.code in (429, 500, 502, 503, 504) and i < tries - 1:
                wait = min(30, 2 ** i * 5)
                print(f"  HTTP {e.code} → retry in {wait}s :: {msg[:160]}", file=sys.stderr)
                time.sleep(wait)
                continue
            raise RuntimeError(f"HTTP {e.code}: {msg[:600]}")
        except (error.URLError, TimeoutError):
            if i < tries - 1:
                time.sleep(min(90, 2 ** i * 5))
                continue
            raise
    raise RuntimeError("unreachable")


def flash_ladder(headers: dict) -> list[str]:
    """Ask the API which models exist, keep the plain Flash ones, newest first. Same rule as the census."""
    req = request.Request(f"{API}/models?pageSize=200", headers=headers)
    with request.urlopen(req, timeout=60) as r:
        ms = json.loads(r.read().decode()).get("models", [])
    ids = [m["name"].split("/", 1)[1] for m in ms if "generateContent" in m.get("supportedGenerationMethods", [])]
    flash = [i for i in ids if "flash" in i.lower() and not re.search(r"image|tts|live|omni|lite|latest|preview|2\.5", i.lower())]

    def ver(s: str):
        m = re.search(r"(\d+)(?:\.(\d+))?", s)
        return (int(m.group(1)), int(m.group(2) or 0)) if m else (0, 0)
    return sorted(flash, key=ver, reverse=True)


# ─────────────────────────────────────────────────────────────────────────────────────────────
# 5. THEN — read the response, keep everything
# ─────────────────────────────────────────────────────────────────────────────────────────────
def part_5_then(resp: dict, out: Path, manifest: dict) -> dict:
    """Find the text inside candidates → content → parts; parse it as JSON; write the raw response,
    the parsed report and the manifest of what was sent. If parsing fails, the raw bytes are still on disk."""
    out.mkdir(parents=True, exist_ok=True)
    text = "".join(part.get("text", "") for c in resp.get("candidates", []) for part in c.get("content", {}).get("parts", []))
    (out / "raw_response.json").write_text(json.dumps(resp, indent=2), encoding="utf-8")
    (out / "request_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    report = json.loads(text)  # raises JSONDecodeError → raw_response.json is already saved
    (out / "audit_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    (out / "audit_report.md").write_text(render_markdown(report, manifest), encoding="utf-8")
    return report


def render_markdown(rep: dict, man: dict) -> str:
    o = rep.get("overall", {})
    lines = [f"# Audit of `{rep.get('artifact', man['artifact']['name'])}` against its SSOTs",
             "",
             f"**Auditor:** {man['model']} · **Generator of the artifact:** {man['generator']} · **Run:** {man['run_utc']}",
             f"**SSOTs sent:** " + ", ".join(f"`{s['name']}`" for s in man["ssots"]),
             "",
             f"**Verdict counts:** supported {o.get('supported', '?')} · contradicted {o.get('contradicted', '?')} · "
             f"not in SSOT {o.get('not_in_ssot', '?')} · uncertain {o.get('uncertain', '?')}",
             "", f"> {o.get('summary', '')}", "",
             "| # | Verdict | Claim in artifact | Location | SSOT | Evidence in SSOT | Note |",
             "|---|---|---|---|---|---|---|"]
    esc = lambda s: str(s).replace("|", "\\|").replace("\n", " ")
    for f in rep.get("findings", []):
        lines.append(f"| {esc(f.get('id',''))} | **{esc(f.get('verdict',''))}** | {esc(f.get('claim_in_artifact',''))} | "
                     f"{esc(f.get('location_in_artifact',''))} | {esc(f.get('ssot',''))} | {esc(f.get('evidence_in_ssot',''))} | {esc(f.get('note',''))} |")
    if rep.get("omissions"):
        lines += ["", "## In the SSOTs, missing from the artifact", "", "| SSOT | Evidence | Note |", "|---|---|---|"]
        for m in rep["omissions"]:
            lines.append(f"| {esc(m.get('in_ssot',''))} | {esc(m.get('evidence',''))} | {esc(m.get('note',''))} |")
    lines += ["", f"*Tokens: {json.dumps(man.get('usage', {}))}. Raw response and request manifest sit beside this file.*"]
    return "\n".join(lines) + "\n"


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


# ─────────────────────────────────────────────────────────────────────────────────────────────
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--artifact", required=True, type=Path)
    ap.add_argument("--ssot", action="append", required=True, type=Path, help="repeatable; order is preserved")
    ap.add_argument("--generator", default="a different LLM", help="who produced the artifact (for the auditor's framing)")
    ap.add_argument("--task", default="Audit the ARTIFACT against the SSOTs below. Findings only.",
                    help="the first text part; keep it short, the auditor role carries the rules")
    ap.add_argument("--model", default=None, help="force one model id; default = newest plain Flash, stepping down on quota")
    ap.add_argument("--key-var", default="GEMINI_API_KEY", help="environment variable holding the key")
    ap.add_argument("--out", default=Path("runs"), type=Path)
    ap.add_argument("--max-output-tokens", default=8192, type=int)
    a = ap.parse_args()

    for p in [a.artifact, *a.ssot]:
        if not p.is_file():
            sys.exit(f"FATAL: not a file: {p}")

    headers = part_2_who(a.key_var)                                        # WHO
    system, contents = part_3_what(a.artifact, a.ssot, a.generator, a.task)  # WHAT
    config = part_4_how(a.max_output_tokens)                               # HOW
    body = {"systemInstruction": system, "contents": contents, "generationConfig": config}
    ladder = [a.model] if a.model else flash_ladder(headers)
    if not ladder:
        sys.exit("FATAL: no usable model id")

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    manifest = {
        "run_utc": stamp, "generator": a.generator, "key_var": a.key_var, "model_ladder": ladder,
        "artifact": {"name": a.artifact.name, "bytes": a.artifact.stat().st_size, "sha256": sha256(a.artifact)},
        "ssots": [{"name": s.name, "bytes": s.stat().st_size, "sha256": sha256(s)} for s in a.ssot],
        "request_bytes": len(json.dumps(body).encode()), "generation_config": config,
    }
    print(f"bundle: {len(a.ssot)} SSOT file(s) + 1 artifact = {manifest['request_bytes']:,} request bytes", file=sys.stderr)

    resp, used = None, None
    for model in ladder:                                                   # WHERE, one rung at a time
        try:
            print(f"→ {model}", file=sys.stderr)
            resp = send(part_1_where(model), headers, body)
            used = model
            break
        except Quota as q:
            print(f"  quota on {model}: {str(q)[:120]} … stepping down", file=sys.stderr)
    if resp is None:
        sys.exit("FATAL: every rung on the ladder is quota-exhausted right now; try later or another --key-var")

    manifest["model"] = used
    manifest["usage"] = resp.get("usageMetadata", {})
    out = a.out / f"{stamp}_{a.artifact.stem[:60]}"
    report = part_5_then(resp, out, manifest)                              # THEN
    o = report.get("overall", {})
    print(f"✓ {used} · supported {o.get('supported')} · contradicted {o.get('contradicted')} · "
          f"not_in_ssot {o.get('not_in_ssot')} · uncertain {o.get('uncertain')} → {out}/audit_report.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
